### ISSUE TITLE
Implement Message Queuing and Event Streaming

### ISSUE THREAD

**Issue by leo-zoho** [leo-zoho/a2#12]
## Message Queuing and Event Streaming Implementation

This issue tracks the implementation of message queuing and event streaming infrastructure for the A2 Execution Engine.

### Apache Kafka Configuration

1. **Kafka Setup** (`infrastructure/messaging/kafka/`)
```yaml
kafka:
  brokers:
    - kafka-0.kafka-headless:9092
    - kafka-1.kafka-headless:9092
    - kafka-2.kafka-headless:9092
  
  topics:
    task_events:
      partitions: 12
      replication: 3
      retention: 168h
      cleanup.policy: delete
    
    system_events:
      partitions: 6
      replication: 3
      retention: 72h
      cleanup.policy: compact
    
    audit_logs:
      partitions: 6
      replication: 3
      retention: 720h
      cleanup.policy: delete
```

### RabbitMQ Configuration

1. **RabbitMQ Setup** (`infrastructure/messaging/rabbitmq/`)
```yaml
rabbitmq:
  hosts:
    - rabbitmq-0.rabbitmq-headless
    - rabbitmq-1.rabbitmq-headless
    - rabbitmq-2.rabbitmq-headless
  
  queues:
    task_queue:
      durable: true
      arguments:
        x-message-ttl: 86400000
        x-dead-letter-exchange: dlx
    
    notification_queue:
      durable: true
      arguments:
        x-message-ttl: 3600000
        x-dead-letter-exchange: dlx
```

### Message Producers

1. **Kafka Producer**
```typescript
// src/common/messaging/kafka/KafkaProducer.ts
class KafkaProducer {
  async connect(): Promise<void>;
  async disconnect(): Promise<void>;
  async send(topic: string, message: KafkaMessage): Promise<void>;
  async sendBatch(topic: string, messages: KafkaMessage[]): Promise<void>;
}

// Example event producer
class TaskEventProducer {
  async publishTaskCreated(task: Task): Promise<void>;
  async publishTaskUpdated(task: Task, changes: TaskChanges): Promise<void>;
  async publishTaskDeleted(taskId: string): Promise<void>;
}
```

2. **RabbitMQ Producer**
```typescript
// src/common/messaging/rabbitmq/RabbitMQProducer.ts
class RabbitMQProducer {
  async connect(): Promise<void>;
  async disconnect(): Promise<void>;
  async sendToQueue(queue: string, message: Buffer, options?: Options.Publish): Promise<boolean>;
  async publish(exchange: string, routingKey: string, message: Buffer): Promise<boolean>;
}

// Example message producer
class NotificationProducer {
  async sendNotification(notification: Notification): Promise<void>;
  async sendBulkNotifications(notifications: Notification[]): Promise<void>;
}
```

### Message Consumers

1. **Kafka Consumer**
```typescript
// src/common/messaging/kafka/KafkaConsumer.ts
class KafkaConsumer {
  async connect(): Promise<void>;
  async disconnect(): Promise<void>;
  async subscribe(topics: string[]): Promise<void>;
  async run(handler: MessageHandler): Promise<void>;
}

// Example event consumer
class TaskEventConsumer {
  async handleTaskCreated(event: TaskCreatedEvent): Promise<void>;
  async handleTaskUpdated(event: TaskUpdatedEvent): Promise<void>;
  async handleTaskDeleted(event: TaskDeletedEvent): Promise<void>;
}
```

2. **RabbitMQ Consumer**
```typescript
// src/common/messaging/rabbitmq/RabbitMQConsumer.ts
class RabbitMQConsumer {
  async connect(): Promise<void>;
  async disconnect(): Promise<void>;
  async consume(queue: string, handler: MessageHandler): Promise<void>;
  async ack(message: Message): Promise<void>;
  async nack(message: Message, requeue?: boolean): Promise<void>;
}

// Example message consumer
class NotificationConsumer {
  async processNotification(notification: Notification): Promise<void>;
  async handleFailedNotification(notification: Notification, error: Error): Promise<void>;
}
```

### Event Schemas

1. **Task Events**
```typescript
interface TaskCreatedEvent {
  type: 'TASK_CREATED';
  payload: {
    taskId: string;
    task: Task;
    timestamp: Date;
  };
}

interface TaskUpdatedEvent {
  type: 'TASK_UPDATED';
  payload: {
    taskId: string;
    changes: TaskChanges;
    timestamp: Date;
  };
}
```

2. **System Events**
```typescript
interface NodeStatusEvent {
  type: 'NODE_STATUS_CHANGED';
  payload: {
    nodeId: string;
    status: NodeStatus;
    timestamp: Date;
  };
}

interface SystemAlertEvent {
  type: 'SYSTEM_ALERT';
  payload: {
    alertId: string;
    severity: AlertSeverity;
    message: string;
    timestamp: Date;
  };
}
```

### Implementation Steps

1. Message Queue Setup:
   - Deploy RabbitMQ cluster
   - Configure high availability
   - Set up monitoring
   - Configure security
   - Set up backups

2. Event Streaming Setup:
   - Deploy Kafka cluster
   - Configure ZooKeeper
   - Set up monitoring
   - Configure security
   - Set up backups

3. Implementation:
   - Create message producers
   - Implement consumers
   - Set up event schemas
   - Add error handling
   - Implement retries

### Validation Steps

- [ ] Set up Kafka cluster
- [ ] Configure Kafka topics
- [ ] Set up RabbitMQ cluster
- [ ] Configure RabbitMQ queues
- [ ] Implement producers
- [ ] Implement consumers
- [ ] Add monitoring
- [ ] Configure security
- [ ] Set up backups
- [ ] Write tests
- [ ] Document setup

### Dependencies

- Requires Kubernetes setup from #5
- Requires monitoring setup from #6
- Supports core services from #8

## Note
Current timestamp: 2025-06-11 03:42:02 UTC
