### ISSUE TITLE
Implement Security and Access Control

### ISSUE THREAD

**Issue by leo-zoho** [leo-zoho/a2#13]
## Security and Access Control Implementation

This issue tracks the implementation of security and access control features for the A2 Execution Engine.

### Authentication Service

1. **OAuth2 Configuration** (`infrastructure/security/oauth2/`)
```yaml
oauth2:
  providers:
    github:
      client_id: ${GITHUB_CLIENT_ID}
      client_secret: ${GITHUB_CLIENT_SECRET}
      callback_url: https://a2.example.com/auth/github/callback
      scopes:
        - read:user
        - user:email
        - repo
    
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      callback_url: https://a2.example.com/auth/google/callback
      scopes:
        - profile
        - email
```

### JWT Configuration

1. **JWT Setup** (`infrastructure/security/jwt/`)
```yaml
jwt:
  access_token:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    expiration: 15m
    algorithm: RS256
  
  refresh_token:
    secret: ${JWT_REFRESH_TOKEN_SECRET}
    expiration: 7d
    algorithm: RS256
```

### Authorization Service

1. **Role-Based Access Control**
```typescript
// src/services/auth/src/models/Permission.ts
interface Permission {
  id: string;
  name: string;
  resource: string;
  action: 'create' | 'read' | 'update' | 'delete' | 'execute';
}

// src/services/auth/src/services/AuthorizationService.ts
class AuthorizationService {
  async hasPermission(userId: string, permission: Permission): Promise<boolean>;
  async grantPermission(userId: string, permission: Permission): Promise<void>;
  async revokePermission(userId: string, permission: Permission): Promise<void>;
  async getUserPermissions(userId: string): Promise<Permission[]>;
}
```

2. **Policy Management**
```typescript
// src/services/auth/src/models/Policy.ts
interface Policy {
  id: string;
  name: string;
  description: string;
  permissions: Permission[];
  conditions: PolicyCondition[];
}

// src/services/auth/src/services/PolicyService.ts
class PolicyService {
  async createPolicy(policy: Policy): Promise<Policy>;
  async updatePolicy(id: string, policy: Partial<Policy>): Promise<Policy>;
  async deletePolicy(id: string): Promise<void>;
  async assignPolicyToRole(policyId: string, roleId: string): Promise<void>;
}
```

### Security Middleware

1. **Authentication Middleware**
```typescript
// src/common/middleware/auth.ts
export const authenticate = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const token = extractToken(req);
    const user = await verifyToken(token);
    req.user = user;
    next();
  } catch (error) {
    res.status(401).json({ error: 'Unauthorized' });
  }
};
```

2. **Authorization Middleware**
```typescript
// src/common/middleware/authorization.ts
export const authorize = (permission: Permission) => {
  return async (req: Request, res: Response, next: NextFunction) => {
    try {
      const hasPermission = await authService.hasPermission(req.user.id, permission);
      if (!hasPermission) {
        throw new Error('Forbidden');
      }
      next();
    } catch (error) {
      res.status(403).json({ error: 'Forbidden' });
    }
  };
};
```

### Security Features

1. **Rate Limiting**
```typescript
// src/common/security/RateLimiter.ts
class RateLimiter {
  async isAllowed(key: string, limit: number, window: number): Promise<boolean>;
  async increment(key: string): Promise<void>;
  async reset(key: string): Promise<void>;
}
```

2. **Request Validation**
```typescript
// src/common/security/RequestValidator.ts
class RequestValidator {
  validate(schema: Schema, data: any): ValidationResult;
  sanitize(data: any, rules: SanitizationRules): any;
}
```

### API Security

1. **API Keys**
```typescript
// src/services/auth/src/models/ApiKey.ts
interface ApiKey {
  id: string;
  key: string;
  name: string;
  permissions: Permission[];
  expiresAt: Date;
  createdBy: string;
}

// src/services/auth/src/services/ApiKeyService.ts
class ApiKeyService {
  async createApiKey(name: string, permissions: Permission[]): Promise<ApiKey>;
  async revokeApiKey(id: string): Promise<void>;
  async validateApiKey(key: string): Promise<boolean>;
  async getApiKeyPermissions(key: string): Promise<Permission[]>;
}
```

### Implementation Steps

1. Authentication Setup:
   - Implement OAuth2 providers
   - Set up JWT handling
   - Create user authentication
   - Add session management
   - Implement MFA support

2. Authorization Setup:
   - Create RBAC system
   - Implement policies
   - Set up permissions
   - Add access control
   - Create audit logging

3. Security Features:
   - Add rate limiting
   - Implement request validation
   - Set up API security
   - Add encryption
   - Implement security headers

### API Endpoints

1. **Authentication API**
```typescript
// Auth endpoints
POST   /api/v1/auth/login
POST   /api/v1/auth/register
POST   /api/v1/auth/refresh
DELETE /api/v1/auth/logout

// OAuth endpoints
GET    /api/v1/auth/:provider
GET    /api/v1/auth/:provider/callback
```

2. **Authorization API**
```typescript
// Role management
POST   /api/v1/roles
GET    /api/v1/roles
PUT    /api/v1/roles/:id
DELETE /api/v1/roles/:id

// Permission management
POST   /api/v1/permissions
GET    /api/v1/permissions
PUT    /api/v1/permissions/:id
DELETE /api/v1/permissions/:id
```

### Validation Steps

- [ ] Set up OAuth2 providers
- [ ] Implement JWT handling
- [ ] Create RBAC system
- [ ] Set up policies
- [ ] Add rate limiting
- [ ] Implement MFA
- [ ] Configure API security
- [ ] Add encryption
- [ ] Set up audit logging
- [ ] Write security tests
- [ ] Document security setup

### Dependencies

- Requires API Gateway from #7
- Requires core services from #8
- Requires data persistence from #11

## Note
Current timestamp: 2025-06-11 03:43:33 UTC
