### ISSUE TITLE
Implement Error Handling and Logging

### ISSUE THREAD

**Issue by leo-zoho** [leo-zoho/a2#14]
## Error Handling and Logging Implementation

This issue tracks the implementation of centralized error handling and logging infrastructure for the A2 Execution Engine.

### Logger Configuration

1. **Winston Logger Setup** (`infrastructure/logging/winston/`)
```typescript
// src/common/logging/config.ts
const loggerConfig = {
  levels: {
    error: 0,
    warn: 1,
    info: 2,
    http: 3,
    debug: 4,
  },
  colors: {
    error: 'red',
    warn: 'yellow',
    info: 'green',
    http: 'magenta',
    debug: 'white',
  },
  transports: {
    console: {
      level: 'debug',
      handleExceptions: true,
      format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.colorize(),
        winston.format.json()
      )
    },
    file: {
      level: 'info',
      filename: 'logs/app.log',
      handleExceptions: true,
      maxsize: 5242880, // 5MB
      maxFiles: 5,
      format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.json()
      )
    }
  }
};
```

### Error Handling

1. **Custom Error Classes**
```typescript
// src/common/errors/CustomError.ts
abstract class CustomError extends Error {
  abstract statusCode: number;
  
  constructor(message: string) {
    super(message);
    Object.setPrototypeOf(this, CustomError.prototype);
  }

  abstract serializeErrors(): { message: string; field?: string }[];
}

// Example specific errors
class ValidationError extends CustomError {
  statusCode = 400;
  
  constructor(public errors: ValidationError[]) {
    super('Invalid request parameters');
    Object.setPrototypeOf(this, ValidationError.prototype);
  }

  serializeErrors() {
    return this.errors.map(err => ({
      message: err.message,
      field: err.field
    }));
  }
}

class NotFoundError extends CustomError {
  statusCode = 404;

  constructor(public resource: string) {
    super(`${resource} not found`);
    Object.setPrototypeOf(this, NotFoundError.prototype);
  }

  serializeErrors() {
    return [{ message: this.message }];
  }
}
```

### Error Middleware

1. **Global Error Handler**
```typescript
// src/common/middleware/error-handler.ts
export const errorHandler = (
  err: Error,
  req: Request,
  res: Response,
  next: NextFunction
) => {
  if (err instanceof CustomError) {
    return res.status(err.statusCode).send({ errors: err.serializeErrors() });
  }

  logger.error({
    error: err,
    message: err.message,
    stack: err.stack,
    path: req.path,
    method: req.method,
    timestamp: new Date().toISOString()
  });

  res.status(500).send({
    errors: [{ message: 'Something went wrong' }]
  });
};
```

### Logging Service

1. **Centralized Logger**
```typescript
// src/common/logging/Logger.ts
class Logger {
  private static instance: Logger;
  private logger: winston.Logger;

  private constructor() {
    this.logger = winston.createLogger(loggerConfig);
  }

  static getInstance(): Logger {
    if (!Logger.instance) {
      Logger.instance = new Logger();
    }
    return Logger.instance;
  }

  error(message: string, meta?: any) {
    this.logger.error(message, meta);
  }

  warn(message: string, meta?: any) {
    this.logger.warn(message, meta);
  }

  info(message: string, meta?: any) {
    this.logger.info(message, meta);
  }

  debug(message: string, meta?: any) {
    this.logger.debug(message, meta);
  }

  http(message: string, meta?: any) {
    this.logger.http(message, meta);
  }
}
```

### Request Logging

1. **HTTP Logger Middleware**
```typescript
// src/common/middleware/http-logger.ts
export const httpLogger = morgan(
  (tokens, req, res) => {
    return JSON.stringify({
      method: tokens.method(req, res),
      url: tokens.url(req, res),
      status: tokens.status(req, res),
      contentLength: tokens.res(req, res, 'content-length'),
      responseTime: tokens['response-time'](req, res),
      userAgent: tokens['user-agent'](req, res),
      timestamp: tokens.date(req, res),
      correlationId: req.headers['x-correlation-id']
    });
  },
  {
    stream: {
      write: (message: string) => {
        logger.http('HTTP Request', JSON.parse(message));
      }
    }
  }
);
```

### Log Aggregation

1. **ELK Stack Configuration** (`infrastructure/logging/elk/`)
```yaml
elasticsearch:
  hosts: 
    - http://elasticsearch:9200
  indices:
    - name: app-logs
      settings:
        number_of_shards: 3
        number_of_replicas: 1
      mappings:
        properties:
          timestamp:
            type: date
          level:
            type: keyword
          message:
            type: text
          meta:
            type: object

logstash:
  input:
    beats:
      port: 5044
  
  filter:
    grok:
      patterns:
        - '%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}'
    
    json:
      source: message
      target: meta
  
  output:
    elasticsearch:
      hosts: ["elasticsearch:9200"]
      index: "app-logs-%{+YYYY.MM.dd}"

kibana:
  host: kibana:5601
  elasticsearch:
    hosts: ["elasticsearch:9200"]
```

### Implementation Steps

1. Logger Setup:
   - Configure Winston logger
   - Set up log rotation
   - Add log formatting
   - Configure log levels
   - Implement log transport

2. Error Handling:
   - Create error classes
   - Implement error middleware
   - Add validation errors
   - Set up error serialization
   - Add error monitoring

3. Log Aggregation:
   - Set up Elasticsearch
   - Configure Logstash
   - Set up Kibana
   - Add log shipping
   - Configure dashboards

### Validation Steps

- [ ] Set up Winston logger
- [ ] Implement error classes
- [ ] Add error middleware
- [ ] Configure log rotation
- [ ] Set up ELK stack
- [ ] Add log shipping
- [ ] Create dashboards
- [ ] Add monitoring
- [ ] Write tests
- [ ] Document setup

### Dependencies

- Requires core services from #8
- Requires monitoring from #6
- Supports API Gateway from #7

### API Examples

1. **Error Response Format**
```json
{
  "errors": [
    {
      "message": "Invalid request parameters",
      "field": "email"
    }
  ],
  "timestamp": "2025-06-11T03:45:21Z",
  "path": "/api/v1/users",
  "correlationId": "123e4567-e89b-12d3-a456-426614174000"
}
```

2. **Log Format**
```json
{
  "level": "error",
  "message": "Failed to process request",
  "timestamp": "2025-06-11T03:45:21Z",
  "correlationId": "123e4567-e89b-12d3-a456-426614174000",
  "meta": {
    "path": "/api/v1/users",
    "method": "POST",
    "statusCode": 400,
    "error": {
      "name": "ValidationError",
      "message": "Invalid email format",
      "stack": "..."
    }
  }
}
```

## Note
Current timestamp: 2025-06-11 03:45:21 UTC
