### ISSUE TITLE
Set up API Gateway and Service Mesh

### ISSUE THREAD

**Issue by leo-zoho** [leo-zoho/a2#7]
## API Gateway and Service Mesh Setup

This issue tracks the implementation of API Gateway (Kong) and Service Mesh (Istio) for the A2 Execution Engine.

### API Gateway Configuration

1. **Kong Configuration** (`infrastructure/gateway/kong/`)
```yaml
_format_version: "2.1"
_transform: true

services:
  - name: task-management
    url: http://task-management:8080
    routes:
      - name: task-api
        paths:
          - /api/v1/tasks
    plugins:
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: key-auth
        config:
          key_names: ["apikey"]

  - name: role-registry
    url: http://role-registry:8080
    routes:
      - name: roles-api
        paths:
          - /api/v1/roles
```

### Service Mesh Configuration

1. **Istio Configuration** (`infrastructure/mesh/istio/`)
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: a2-services
spec:
  hosts:
  - "*"
  gateways:
  - a2-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1/tasks
    route:
    - destination:
        host: task-management
        port:
          number: 8080
  - match:
    - uri:
        prefix: /api/v1/roles
    route:
    - destination:
        host: role-registry
        port:
          number: 8080
```

### Implementation Steps

1. API Gateway Setup:
   - Deploy Kong Gateway
   - Configure routes
   - Set up authentication
   - Implement rate limiting
   - Configure SSL/TLS

2. Service Mesh Setup:
   - Install Istio
   - Configure sidecars
   - Set up traffic routing
   - Implement circuit breakers
   - Configure mTLS

3. Security Configuration:
   - API authentication
   - Service-to-service authentication
   - Network policies
   - SSL/TLS certificates
   - API key management

### Gateway Features

1. **Authentication and Authorization**
   - API key authentication
   - JWT validation
   - OAuth2 integration
   - Rate limiting
   - IP whitelisting

2. **Traffic Management**
   - Load balancing
   - Circuit breaking
   - Retry policies
   - Timeout configuration
   - Traffic splitting

### Service Mesh Features

1. **Service Discovery**
   - Automatic service registration
   - Health checking
   - Load balancing
   - Circuit breaking
   - Retry policies

2. **Security**
   - mTLS between services
   - Authorization policies
   - Certificate management
   - Traffic encryption
   - Access control

### Configuration Structure

```
infrastructure/
├── gateway/
│   └── kong/
│       ├── config/
│       │   ├── kong.yaml
│       │   └── plugins/
│       └── deployment/
└── mesh/
    └── istio/
        ├── config/
        │   ├── gateway.yaml
        │   └── virtual-services/
        └── deployment/
```

### Validation Steps

- [ ] Deploy API Gateway
- [ ] Configure service routes
- [ ] Set up authentication
- [ ] Install service mesh
- [ ] Configure service mesh policies
- [ ] Test service-to-service communication
- [ ] Verify security policies
- [ ] Document gateway and mesh setup

### Dependencies

- Requires Kubernetes setup from #5
- Requires service deployments to be operational
- Relates to monitoring setup in #6

## Note
Current timestamp: 2025-06-11 02:26:31 UTC
